### ISSUE TITLE
Having main AND master branch is confusing

### ISSUE THREAD

**Issue by sbutzek** [SAP-samples/teched2020-DEV267#16]
Can we delete the master branch? I am constantly getting confused that there is "main" and "master".

**Comment by maximnaidenov** [comment]
I am fine with this.

**Comment by sbutzek** [comment]
> I am fine with this.

Great :) Unfortuantely I don't have the neccessary rights, can you do it @maximnaidenov?

**Comment by sbutzek** [comment]
@georgbischoff deleted the master branch, therefore we can close this.
